services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: ""
      ND_API_ENABLED: "true"  # 启用 API
    volumes:
      - ./data:/data
      - ./music:/music:ro