version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: ""
      ND_API_ENABLED: "true"  # 启用 API
    volumes:
      - /opt/navidrome/data:/data"  #音乐文件左侧为安装位置
      - /opt/navidrome/music:/music:ro" #音乐文件左侧为安装位置